#!/bin/bash

# Proporción tapa:         H/W = 1.41
# Proporción horizontal:   W/H = 1.65
# Proporción vertical:     H/W = 2.42
# Proporción imagen menor: H/W = 1.21

if [ -z "$(which convert)" ]; then
	echo Comando convert the ImageMagick no encontrado.
	exit 2
fi

ancho=2119
alto=2568
tamfoto="$ancho"x"$alto"
fondo="xc:black"
paginas=plantillas

function buscar_fotos()
{
	fotos=($(ls ./*.jpg ./*.JPG ./*.png ./*.PNG ./*.gif ./*.GIF 2>/dev/null))
	cfotos=${#fotos[@]}

	for (( i=0; i < cfotos; i++ ))
	do
		foto=${fotos[$i]}

		if [ "${foto: -4}" != ".png" ] && [ "${foto: -4}" != ".PNG" ]; then
			nombre="${foto%.*}"
			echo Convirtiendo "$dir/$foto" a "$dir/$nombre.png"
			if convert "$foto" "$nombre.png"; then
				rm "$foto" 2>/dev/null
				fotos[$i]=$nombre.png
				foto=$nombre.png
			else
				fotos[$i]=$foto
			fi
		fi
	done
}

function vertical()
{
	echo Mes "$mes": Formato vertical en "$dir" para "$cfotos" fotos.
	case "$cfotos" in
		0)
			echo "    No hay fotos."
			;;
		1)
			echo "    Una: ${fotos[0]}"
			cp "${fotos[0]}" "$target"
			;;
		2)
			echo "    Izquierda:  ${fotos[0]}"
			echo "    Derecha:    ${fotos[1]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 2119x1284 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 2119x1284 \) -geometry +0+1284  -composite \
					"$target"
			;;
		3)
			echo "    Foto grande:  ${fotos[0]}"
			echo "    Foto chica 1: ${fotos[1]}"
			echo "    Foto chica 2: ${fotos[2]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 1059x2568 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 1060x1284 \) -geometry +1059+0  -composite \
					\( "${fotos[2]}" -resize 1060x1284 \) -geometry +1059+1284  -composite \
					"$target"
			;;
		*)
			echo "    Foto arriba izq:  ${fotos[0]}"
			echo "    Foto arriba der: ${fotos[1]}"
			echo "    Foto abajo  izq: ${fotos[2]}"
			echo "    Foto abajo  der: ${fotos[3]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 1060x1284 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 1060x1284 \) -geometry +1059+0  -composite \
					\( "${fotos[2]}" -resize 1060x1284 \) -geometry +0+1284  -composite \
					\( "${fotos[3]}" -resize 1060x1284 \) -geometry +1059+1284  -composite \
					"$target"
			;;
	esac
}

function horizontal()
{
	echo Mes "$mes": Formato horizontal en "$dir" para "$cfotos" fotos.
	case "$cfotos" in
		0)
			echo "    No hay fotos."
			;;
		1)
			echo "    Una: ${fotos[0]}"
			cp "${fotos[0]}" "$target"
			;;
		2)
			echo "    Izquierda:  ${fotos[0]}"
			echo "    Derecha:    ${fotos[1]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 1059x2568 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 1060x2568 \) -geometry +1059+0  -composite \
					"$target"
			;;
		3)
			echo "    Foto grande:  ${fotos[0]}"
			echo "    Foto chica 1: ${fotos[1]}"
			echo "    Foto chica 2: ${fotos[2]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 2119x1284 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 1059x1284 \) -geometry +0+1284  -composite \
					\( "${fotos[2]}" -resize 1060x1284 \) -geometry +1059+1284  -composite \
					"$target"
			;;
		*)
			echo "    Foto arriba izq:  ${fotos[0]}"
			echo "    Foto arriba der: ${fotos[1]}"
			echo "    Foto abajo  izq: ${fotos[2]}"
			echo "    Foto abajo  der: ${fotos[3]}"
			convert -size "$tamfoto" "$fondo" \
					\( "${fotos[0]}" -resize 1060x1284 \) -geometry +0+0   -composite \
					\( "${fotos[1]}" -resize 1060x1284 \) -geometry +1059+0  -composite \
					\( "${fotos[2]}" -resize 1060x1284 \) -geometry +0+1284  -composite \
					\( "${fotos[3]}" -resize 1060x1284 \) -geometry +1059+1284  -composite \
					"$target"
			;;
	esac
}

function procesar_mes()
{
	if (( "$mes" < "10" )); then
		smes=0$mes
	else
		smes=$mes
	fi

	dir=$(find . -maxdepth 1 -type d -print | grep -E "$smes"'[HhVv]?' | head -1)

	if [[ -d $dir ]]; then
		dest=$(pwd)
		target=$dest/fotomes$mes.png
		pushd "$dir" > /dev/null
		buscar_fotos
		if echo "$dir" | grep -qE '''[Hh]$'''
		then
			horizontal
		else
			vertical
		fi
		popd > /dev/null
		if [[ -e "fotomes$mes.png" ]]; then
			if convert "$paginas/$smes.png" \( "fotomes$mes.png" -resize "$tamfoto" \) -geometry +0+0 -composite "pag$smes.png"; then
				pagina[$mes]=pag$smes.png
			fi
			rm "fotomes$mes.png" 2>/dev/null
		fi
	else
		echo Mes "$mes": ADVERTENCIA: Directorio no encontrado.
	fi
}

function procesar_tapa()
{
	tapa=$(find . -iname 'tapa*.jpg' -or -iname 'tapa*.JPG' -or -iname 'tapa*.png' -or -iname 'tapa*.gif' | tail -1)

	if [ -n "$tapa" ]; then
		if [ -f "$tapa" ]; then
			if [ "${tapa: -4}" != ".png" ]; then
				nombre="${tapa%.*}"
				echo Convirtiendo "$tapa" a "$nombre.png"
				if convert "$tapa" "$nombre.png"; then
					rm "$tapa" 2>/dev/null
					tapa="$nombre.png"
				fi
			fi
			echo Usando "$tapa" como tapa del calendario...
			convert "$tapa" -resize 2480x3508 "$tapa"
		else
			echo "$tapa" no es un archivo valido para la tapa.
			unset tapa
		fi
	else
		echo Tapa no encontrada.
		unset tapa
	fi
}

function ayuda()
{
	echo Usos: "$0" dir
	echo "		$0" -c dir
}

function crear_calendario()
{
	if [ -d "$proyecto" ]; then
		echo Creando calendario para "$proyecto"...
	else
		echo "$proyecto" no es un directorio valido.
		exit 2
	fi

	pushd "$proyecto" > /dev/null

	procesar_tapa

	for (( mes=1; mes <= 12; mes++ ))
	do
		procesar_mes
	done

	echo "Compaginando ${#pagina[@]} paginas..."
	if [[ -e "$tapa" ]]; then
		convert "$tapa" "${pagina[@]}" -page A4 -quality 100 "calendario_$proyecto.pdf"
	else
		convert "${pagina[@]}" -page A4 -quality 100 "calendario_$proyecto.pdf"
	fi
	rm "${pagina[@]}" 2>/dev/null

	popd > /dev/null
}

function crear_proyecto()
{
	echo Creando proyecto "$nuevo"...
	mkdir -p "$nuevo"
	pushd "$nuevo" > /dev/null
	for m in 01 02 03 04 05 06 07 08 09 10 11 12
	do
		mkdir "$m"
	done
	mkdir "$paginas"
	popd > /dev/null
	echo Hecho. Copie las plantillas en "$nuevo/$paginas"
	echo y las fotos para cada mes en el subdirectorio correspondiente.
}

if [ -z "$1" ]; then
	ayuda
	exit 1
fi

clave="$1"
case $clave in
	-c|--crear)
		nuevo="$2"
		crear_proyecto
		;;
	*)
		proyecto="$1"
		crear_calendario
	;;
esac

exit 0

